CREATE TABLE Users(
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(100)
);

CREATE TABLE EventGroups(
    EventGroupID INT PRIMARY KEY AUTO_INCREMENT,
    EventGroupName VARCHAR(100),
    FKUserID INT,
    FOREIGN KEY(FKUserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Events(
    EventID INT PRIMARY KEY AUTO_INCREMENT,
    EventName VARCHAR(100),
    EventStartDateTime DATETIME,
    EventEndDateTime DATETIME,
    FKEventGroupID INT,
    FKUserID INT,
    FOREIGN KEY(FKEventGroupID) REFERENCES EventGroups(EventGroupID) ON DELETE CASCADE,
    FOREIGN KEY(FKUserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
